trigger:
- main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

  variables:
  CODECOV_TOKEN: $(CODECOV_TOKEN)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build app'
  
  - script: |
    npm test -- --coverage
  displayName: 'Run tests with coverage'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build files to staging'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
    replaceExistingArchive: true
  displayName: 'Archive build folder'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'
    appName: 'U-Collab'
    package: '$(Build.ArtifactStagingDirectory)/build.zip'
  displayName: 'Deploy to Azure Web App'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov
      chmod +x codecov
      ./codecov -t $CODECOV_TOKEN -f coverage/lcov.info
  displayName: 'Upload coverage to Codecov'
